### ISSUE TITLE
Items Module Issue

### ISSUE THREAD

**Issue by noonnightcoder** [monydara/Sale-system#5]
@monydara Here is what I tested so far and found it the bugs :	

- Issue: Item => quick category creation error
- Issue: Item => After create current in General Setup module does not appear in Item => currency selection
- Issue: Item => quick UM creation does not work
- Issue: Items => UOM creation error and log out page
<img width="769" alt="screen shot 2017-11-27 at 1 46 41 pm" src="https://user-images.githubusercontent.com/5521789/33254046-7ab4c41c-d379-11e7-8c8e-c50929ac0c50.png">

**Comment by monydara** [comment]
ok bong got it .

**Comment by monydara** [comment]
all problem is solve . please bong check again .

**Comment by monydara** [comment]
every done  bong . please check

**Comment by noonnightcoder** [comment]
Okay let me checked - thanks
